### ISSUE TITLE
trained voxbind model or pretrained models

### ISSUE THREAD

**Issue by MachineGUN001** [Genentech/Voxbind#1]
Hi,

Thank you very much for providing such meaningful work. Could you please provide or share a trained voxbind model or pretrained models for easier validation and running of models?

many thanks,

best,
Sh-Y

**Comment by poliveirap** [comment]
Hi Sh-Y,

Sorry for the late reply. 
Unfortunately, we are not authorized by the Legal to release the weights at this point. Once/if this change, I will upload them on the repo.

Cheers,
Pedro
